CIRCUITPY_PYSTACK_SIZE = 12288

[LJINUX]
serial_console = true
usb_access = false
leden = -1
ledtype = "neopixel"
led = 33
DEBUG = false
root_SCLK = -1
root_SCSn = -1
root_MOSI = -1
root_MISO = -1

[IWD]
#Network1 = "password1"
#Network2 = "password2"

[IWD-AP]
SSID = "ljinux"
PASSWD = "ljinuxingallovertheplace"
