CIRCUITPY_PYSTACK_SIZE = 12288

[BERYLLIUM]
setup = true

fs_label = "BERYLLIUM"

serial_console_enabled = true
usb_msc_available = true
usb_hid_available = true
usb_midi_available = true
wifi_available = true
ble_available = false
blc_available = false
usb_msc_enabled = false
usb_hid_enabled = false
usb_midi_enabled = false
tz_offset = 2

ledtype = "none"
led = "none"

DEBUG = false

[IWD]
#Network1 = "password1"
#Network2 = "password2"

[IWD-AP]
#SSID = "beryllium-ap"
#PASSWD = "CHANGEME WIFI PASSWORD"

[TWM]
brightness = 80
suspend_brightness = 2
alarm = 0
sounds = true
notification_sound = false
alarm_sound = false
timer_sound = false

[RFKILL]
wlan = false
bluetooth = false

[SNAKE]
hearts = 3
score = 0
level = 0
apple_power = 0
next_move = 0
prev_move = 0
chain = "8|7|2|9|7|6|10|7|8"
apples = ""
hscores = "0|0|0|0|0"
