CIRCUITPY_PYSTACK_SIZE = 4608

[LJINUX]
setup = true

fs_label = "LJINUX"

serial_console_enabled = true
usb_msc_available = true
usb_hid_available = true
usb_midi_available = true
wifi_available = false
ble_available = false
blc_available = false
usb_msc_enabled = false
usb_hid_enabled = false
usb_midi_enabled = false

ledtype = "neopixel"
led = "NEOPIXEL"

DEBUG = false
