CIRCUITPY_PYSTACK_SIZE = 4608

[LJINUX]
setup = true
serial_console = true
usb_access = false
usb_hid = false
leden = -1
ledtype = "generic"
led = -1
DEBUG = false
root_SCLK = -1
root_SCSn = -1
root_MOSI = -1
root_MISO = -1
