CIRCUITPY_PYSTACK_SIZE = 12288

[LJINUX]
setup = true

fs_label = "LJINUX"

serial_console_enabled = true
usb_msc_available = true
usb_hid_available = true
usb_midi_available = true
wifi_available = true
ble_available = false
blc_available = false
usb_msc_enabled = false
usb_hid_enabled = false
usb_midi_enabled = false

leden = -1
ledtype = "generic"
led = -1

DEBUG = false

root_SCLK = -1
root_SCSn = -1
root_MOSI = -1
root_MISO = -1

[IWD]
#Network1 = "password1"
#Network2 = "password2"

[IWD-AP]
SSID = "ljinux"
PASSWD = "ljinuxingallovertheplace"
