name: Black code formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: |
          pip install pipenv
          touch pipenv
          pipenv install --deploy --dev --system
      - uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.SECRET }}
          black: true
          auto_fix: true
