name: Compile test

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      
      - name: Run make compiletest
        working-directory: source
        run: |
          make compiletest
